theme: light

# Chiave per la validazione dell'identità (reset password)
identity_validation:
  reset_password:
    jwt_secret: 'smartcityhub_jwt_secret_laboratorio_2024_molto_lungo'

server:
  address: 'tcp://:9091'
  endpoints:
    authz:
      forward-auth:
        implementation: 'ForwardAuth'

log:
  level: debug

totp:
  issuer: smartcityhub

authentication_backend:
  file:
    path: /config/users_database.yml

session:
  secret: 'smartcityhub_session_secret_laboratorio_2024_molto_lungo'
  cookies:
    - domain: '127.0.0.1'
      authelia_url: 'http://127.0.0.1:9091'
      default_redirection_url: 'http://127.0.0.1'
      expiration: 1h
      inactivity: 5m

storage:
  encryption_key: 'smartcityhub_encryption_key_laboratorio_2024_molto_lungo'
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt

access_control:
  default_policy: one_factor
  rules:
    - domain: '127.0.0.1'
      policy: one_factor